services:
  persephone:
    build:
      context: .
      args:
        - PREFIX=$PREFIX
    image: persephone
    container_name: persephone
    environment:
      - PYTHONPATH=/src
    secrets:
      - bot_token
      - owner_id
      - personality
      - openai_api_key
      - dezgo_api_key
      - google_api_key
      - google_engine_id

secrets:
  bot_token:
    external: true
  owner_id:
    external: true
  personality:
    external: true
  openai_api_key:
    external: true
  dezgo_api_key:
    external: true
  google_api_key:
    external: true
  google_engine_id:
    external: true
